# Generated by Django 2.2 on 2021-07-14 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quest_text',
            new_name='question_text',
        ),
    ]
